/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Practica3;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TemasFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TemasFrame.class.getName());

    private Asignatura materia;
    
    private GridLayout gridLayout = new GridLayout(1, 1);
    
    public TemasFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    public TemasFrame(Asignatura materia){
        initComponents();
        
        panelListaTemas.setLayout(gridLayout);
        
        this.materia = materia;
        
        if(materia.getTemas() == null ) {
            materia.setTemas(new ArrayList<>());
        }
        
        setLocationRelativeTo(null);
        
        labelMateria.setText(
            "Temas de : \n" + this.materia.getNombreAsignatura()
        );
        
        mostrarTemas();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMateria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListaTemas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Temas");

        labelMateria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMateria.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Temas");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Nuevo tema");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelListaTemas.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelListaTemasLayout = new javax.swing.GroupLayout(panelListaTemas);
        panelListaTemas.setLayout(panelListaTemasLayout);
        panelListaTemasLayout.setHorizontalGroup(
            panelListaTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        panelListaTemasLayout.setVerticalGroup(
            panelListaTemasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelListaTemas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreTema = JOptionPane.showInputDialog(
            "Nombre del nuevo tema"
        );
        
        Tema t = new Tema();
        t.setNombreTema(nombreTema);
        t.setNumTema(materia.getTemas().size() + 1);
        
        materia.getTemas().add(t);
        
        JOptionPane.showMessageDialog(null,"Tema agregado");
        mostrarTemas();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void mostrarTemas(){
        panelListaTemas.removeAll();
        gridLayout.setRows(materia.getTemas().size());
        
        // Version 1 sin borrar
        /*for(Tema t : materia.getTemas()) {
            TemaPanel tp = new TemaPanel(this, t);
            panelListaTemas.add(tp);
        }*/
        
        // Version 2 con borrado
        ArrayList<Tema> temas = materia.getTemas();
        for (int i = 0; i < temas.size(); i++) {
            TemaPanel tp = new TemaPanel(this, temas, i);
            panelListaTemas.add(tp);
        }
        
        panelListaTemas.updateUI();
            
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TemasFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMateria;
    private javax.swing.JPanel panelListaTemas;
    // End of variables declaration//GEN-END:variables
}
