/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Practica4;

import Practica4.models.Venta;
import Practica4.services.VentaService;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class HistorialPanel extends javax.swing.JPanel {
    
    private final String IMG_PATH = "src/main/java/Practica4/images/";
    private int indice;
    
    private Venta venta;
    private ArrayList<Venta> ventas;
    
    public HistorialPanel(int indice) {
        initComponents();
        
        this.ventas = VentaService.getVentas();
        this.venta = ventas.get(indice);
        
        labelNombre.setText(venta.getProducto().getNombreProducto());
        labelCantidad.setText(String.format("%s", venta.getCantidadVendida()));
        labelTotal.setText(String.format("$%1$,.2f", venta.getTotal()));
        labelFecha.setText(venta.getFecha());
        
        panelImage1.setIcon(
                new javax.swing.ImageIcon(
                    IMG_PATH + venta.getProducto().getFotoProducto()
                )
            );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 0));
        setForeground(new java.awt.Color(153, 255, 0));

        labelNombre.setFont(new java.awt.Font("Franklin Gothic Book", 0, 17)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombre.setText("jLabel1");

        panelImage1.setBackground(new java.awt.Color(204, 255, 204));
        panelImage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelImage1.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        label3.setFont(new java.awt.Font("Fira Mono", 1, 15)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 0, 0));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("Unidades: ");

        label4.setFont(new java.awt.Font("Fira Mono", 1, 15)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 0, 0));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("Total: ");

        label5.setFont(new java.awt.Font("Fira Mono", 1, 15)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 0, 0));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Fecha: ");

        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(0, 0, 0));
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelFecha.setText("dd/mm/yyyy");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(0, 0, 0));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTotal.setText("$--.--");

        labelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        labelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCantidad.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3)
                            .addComponent(label4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label5)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3)
                            .addComponent(labelCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label4)
                            .addComponent(labelTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label5)
                            .addComponent(labelFecha))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTotal;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
