package Practica4;

import Practica4.models.Venta;
import Practica4.services.VentaService;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
 public class HistorialFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistorialFrame.class.getName());

    private ArrayList<Venta> ventas;
    
    private GridLayout gridLayout = new GridLayout(1, 1);
    
    private double total;
    private int criterio;
    
    public HistorialFrame() {
        initComponents();
        
        panelVentas.setLayout(gridLayout);
        
        
        this.ventas = VentaService.getVentas();
        criterio = 3;
        
        setLocationRelativeTo(null);
        
        mostrarVentas();
        
        labelTextoBusqueda.setVisible(false);
        labelFechaAyuda.setVisible(false);
        fieldBusqueda.setVisible(false);
        btnBuscar.setVisible(false);
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCriterio = new javax.swing.ButtonGroup();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelTextoBusqueda = new javax.swing.JLabel();
        fieldBusqueda = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelVentas = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        labelTotal = new javax.swing.JLabel();
        critFecha = new javax.swing.JRadioButton();
        critProd = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        labelFechaAyuda = new javax.swing.JLabel();
        critTodos = new javax.swing.JRadioButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Temas");

        labelTextoBusqueda.setFont(new java.awt.Font("Bookman Old Style", 0, 15)); // NOI18N
        labelTextoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        labelTextoBusqueda.setText("Hola");

        fieldBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        fieldBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        fieldBusqueda.setForeground(new java.awt.Color(0, 0, 0));

        label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Historial de ventas");

        panelVentas.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelVentas);

        labelTotal.setFont(new java.awt.Font("Franklin Gothic Book", 0, 24)); // NOI18N
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotal.setText("Total");
        labelTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        grupoCriterio.add(critFecha);
        critFecha.setText("Fecha");
        critFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                critFechaActionPerformed(evt);
            }
        });

        grupoCriterio.add(critProd);
        critProd.setText("Nombre");
        critProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                critProdActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        labelFechaAyuda.setFont(new java.awt.Font("Bookman Old Style", 0, 15)); // NOI18N
        labelFechaAyuda.setForeground(new java.awt.Color(0, 0, 0));
        labelFechaAyuda.setText("Formato de fecha: yyyy-mm-dd");

        grupoCriterio.add(critTodos);
        critTodos.setText("Todos");
        critTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                critTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTextoBusqueda)
                                    .addComponent(fieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(btnBuscar))
                            .addComponent(labelFechaAyuda))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(critFecha)
                            .addComponent(critTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(critProd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(filler5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTextoBusqueda)
                            .addComponent(critProd))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelFechaAyuda))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(critFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(critTodos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelTotal))
                    .addComponent(filler6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void critFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_critFechaActionPerformed
        labelTextoBusqueda.setText("Inserte la fecha:");
        fieldBusqueda.setText("");
        criterio = 1;
        
        labelTextoBusqueda.setVisible(true);
        labelFechaAyuda.setVisible(true);
        btnBuscar.setVisible(true);
        fieldBusqueda.setVisible(true);
    }//GEN-LAST:event_critFechaActionPerformed

    private void critProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_critProdActionPerformed
        labelTextoBusqueda.setText("Inserte el nombre del producto:");
        fieldBusqueda.setText("");
        criterio = 2;

        labelTextoBusqueda.setVisible(true);
        labelFechaAyuda.setVisible(false);
        btnBuscar.setVisible(true);
        fieldBusqueda.setVisible(true);

    }//GEN-LAST:event_critProdActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(criterio != 3){
            switch (criterio) {
                case 1 -> {
                    if(fieldBusqueda.getText().length() < 1)
                    {
                        JOptionPane.showMessageDialog(null,
                                    "Caja de texto vacia",
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                                );
                        break;
                    }
                    mostrarPorFecha(fieldBusqueda.getText());
                    fieldBusqueda.setText("");
                }
                case 2 -> {
                    if(fieldBusqueda.getText().length() < 1)
                    {
                        JOptionPane.showMessageDialog(null,
                                    "Caja de texto vacia",
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                                );
                        break;
                    }
                    mostrarPorNombre(fieldBusqueda.getText().toUpperCase());
                    fieldBusqueda.setText("");
                }
                default -> System.out.println("XD");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void critTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_critTodosActionPerformed
        criterio = 3;
        
        labelTextoBusqueda.setVisible(false);
        labelFechaAyuda.setVisible(false);
        fieldBusqueda.setVisible(false);
        btnBuscar.setVisible(false);
        
        mostrarVentas();
    }//GEN-LAST:event_critTodosActionPerformed
    
    
    private void mostrarPorFecha(String fecha){
        panelVentas.removeAll();
        
        int size = 0;
        total = 0;
        
        for (int i = 0; i < ventas.size(); i++) {
            HistorialPanel hp = new HistorialPanel(i);
            System.out.println(ventas.get(i).getFecha().substring(0,10));
            if(fecha.equals(ventas.get(i).getFecha().substring(0,10))){
                total += ventas.get(i).getTotal();
                panelVentas.add(hp);
                size++;
            }
            

        }
        gridLayout.setRows(size);
        
        panelVentas.updateUI();
        labelTotal.setText(String.format(" TOTAL VENTAS: $%1$,.2f", total));  
        
        if(size == 0) 
            JOptionPane.showMessageDialog(null, 
                "No se encontro ventas asociadas a la fecha buscada", 
                "Sin resultados",
                JOptionPane.ERROR_MESSAGE
            );
    }
    
    private void mostrarPorNombre(String nombre){
        panelVentas.removeAll();
        
        int size = 0;
        total = 0;
        
        for (int i = 0; i < ventas.size(); i++) {
            HistorialPanel hp = new HistorialPanel(i);
            System.out.println(ventas.get(i).getProducto().getNombreProducto());
            if(nombre.equals(ventas.get(i).getProducto().getNombreProducto().toUpperCase())){
                total += ventas.get(i).getTotal();
                panelVentas.add(hp);
                size++;
            }
            
        }
        gridLayout.setRows(size);
        
        panelVentas.updateUI();
        labelTotal.setText(String.format(" TOTAL VENTA: $%1$,.2f", total));   
        
        if(size == 0) 
            JOptionPane.showMessageDialog(null, 
                "No se encontro ventas asociadas al producto buscado", 
                "Sin resultados",
                JOptionPane.ERROR_MESSAGE
            );
    }
    
    private void mostrarVentas(){
        panelVentas.removeAll();
        gridLayout.setRows(ventas.size());
        total = 0;
        
        // Version 1 sin borrar
        /*for(Tema t : materia.getTemas()) {
            TemaPanel tp = new TemaPanel(this, t);
            panelListaTemas.add(tp);
        }*/
        
        // Version 2 con borrado
        for (int i = 0; i < ventas.size(); i++) {
            HistorialPanel hp = new HistorialPanel(i);
            total += ventas.get(i).getTotal();
            panelVentas.add(hp);
        }
        panelVentas.updateUI();
        labelTotal.setText(String.format(" TOTAL VENTA: $%1$,.2f", total));   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HistorialFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JRadioButton critFecha;
    private javax.swing.JRadioButton critProd;
    private javax.swing.JRadioButton critTodos;
    private javax.swing.JTextField fieldBusqueda;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.ButtonGroup grupoCriterio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelFechaAyuda;
    private javax.swing.JLabel labelTextoBusqueda;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelVentas;
    // End of variables declaration//GEN-END:variables
}
