package Practica3.core_views;


import Practica3.admin_views.AdminFrame;
import Practica3.client_views.ClientFrame;
import Practica3.model_layer.Usuario;
import Practica3.services.UsuarioService;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Link
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    private final UsuarioService userService = new UsuarioService();

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPass = new javax.swing.JPasswordField();
        btnAcceder = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña:");

        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        btnRegistrar.setForeground(new java.awt.Color(102, 0, 255));
        btnRegistrar.setText("Registrarse");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldUsuario)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fieldPass)
                    .addComponent(btnAcceder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAcceder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        String errores = valida();
        if(errores.isEmpty()) {
            try {
                Usuario u = userService.findUser(
                        fieldUsuario.getText(),
                        fieldPass.getText()
                );

                if(u != null) {
                    if(u.isEs_admin()){
                        new AdminFrame(u).setVisible(true);
                        return;
                    }
                    new ClientFrame(u).setVisible(true);
                }else {
                    JOptionPane.showMessageDialog(
                            null, "Usuario incorrecto, revise el usuario y/o contraseña"
                    );
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(
                        null, "Error al acceder"
                );
            }
        }
        JOptionPane.showMessageDialog(null, errores,"Tienes errores", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String errores = valida();
        if(errores.isEmpty()) {
            try {
                boolean result = userService.addUser(
                        fieldUsuario.getText(),
                        fieldPass.getText()
                );

                if(result) {
                    JOptionPane.showMessageDialog(null, "Usuario registrado");
                    return;
                }
                else {
                    JOptionPane.showMessageDialog(
                            null, "Usuario no registrado."
                    );
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(
                        null, "Error al registrar"
                );
            }
        }
        JOptionPane.showMessageDialog(null, errores,"Tienes errores", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_btnRegistrarActionPerformed

    public  void showBack(){
        this.setVisible(true);
    }

    private String valida(){
        String errores = "";
        if(fieldUsuario.getText().length() <= 2) {
            errores += "\nEl usuario debe tener al menos 3 caracteres";
            fieldUsuario.setBackground(Color.yellow);
        }
        if(fieldPass.getText().length() <= 2) {
            errores += "\nLa contraseña debe tener al menos 3 caracteres";
            fieldPass.setBackground(Color.yellow);
        }
        return errores;
    }

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPasswordField fieldPass;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}