/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Practica3;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AsignaturaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AsignaturaFrame.class.getName());
    
    private CapturadorTemariosFrame capturador;
    private ArrayList<Asignatura> asignaturas;
    private Asignatura materia;
    
    /**
     * Creates new form AsignaturaFrame
     */
    public AsignaturaFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(Color.cyan);

    }
    
    public AsignaturaFrame(CapturadorTemariosFrame capturador,
            Asignatura materia) {
        initComponents();
        
        this.capturador = capturador;
        this.materia = materia;
        
        setLocationRelativeTo(null);        
        getContentPane().setBackground(Color.cyan);
        
    }
    
    public AsignaturaFrame( CapturadorTemariosFrame capturador,
            ArrayList<Asignatura> asignaturas, 
            Asignatura materia){
        initComponents();
        
        this.capturador = capturador;
        this.materia = materia;
        this.asignaturas = asignaturas;
        
        setLocationRelativeTo(null);        
        getContentPane().setBackground(Color.cyan);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldNombreAsignatura = new javax.swing.JTextField();
        fieldClaveAsignatura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelSemestre = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        btnGuardarAgregar = new javax.swing.JButton();
        btnGuardarFinalizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guardar Asignatura");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        fieldNombreAsignatura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNombreAsignaturaFocusLost(evt);
            }
        });
        fieldNombreAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreAsignaturaActionPerformed(evt);
            }
        });

        fieldClaveAsignatura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldClaveAsignaturaFocusGained(evt);
            }
        });
        fieldClaveAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldClaveAsignaturaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre asignatura");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Clave asignatura");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Semestre");

        labelSemestre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSemestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSemestre.setText("1");

        jSlider1.setMaximum(9);
        jSlider1.setToolTipText("");
        jSlider1.setValue(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Creditos");

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10.0d, 0.1d));

        btnGuardarAgregar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardarAgregar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnGuardarAgregar.setForeground(new java.awt.Color(51, 153, 0));
        btnGuardarAgregar.setText("Guardar y agregar más");
        btnGuardarAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAgregarActionPerformed(evt);
            }
        });

        btnGuardarFinalizar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardarFinalizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnGuardarFinalizar.setForeground(new java.awt.Color(0, 153, 0));
        btnGuardarFinalizar.setText("Guardar y finalizar");
        btnGuardarFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFinalizarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(204, 0, 51));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldClaveAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(28, 28, 28)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(labelSemestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldClaveAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAgregar)
                    .addComponent(btnGuardarFinalizar))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreAsignaturaActionPerformed

    private void fieldClaveAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldClaveAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldClaveAsignaturaActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        String strSemestre = "" + jSlider1.getValue();
        labelSemestre.setText(strSemestre);
    }//GEN-LAST:event_jSlider1StateChanged

    private void fieldNombreAsignaturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreAsignaturaFocusLost
        String nombreAsignatura = fieldNombreAsignatura.getText();
        nombreAsignatura = nombreAsignatura.toUpperCase().trim();
        fieldNombreAsignatura.setText(nombreAsignatura);
    }//GEN-LAST:event_fieldNombreAsignaturaFocusLost

    private void fieldClaveAsignaturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldClaveAsignaturaFocusGained
        String claveAsignatura = fieldClaveAsignatura.getText();
        if(claveAsignatura.trim().isEmpty()) {
            String nombreAsignatura = fieldNombreAsignatura.getText();
            String [] partes = nombreAsignatura.split(" ");
            String clave = " ";
            for(String parte: partes) { //For each o For mejorado
                clave += parte.substring(0,1).toUpperCase(); //Se agrega a la cadeana: +=
            }
            clave += "-";
            fieldClaveAsignatura.setText(clave);
        }                    
    }//GEN-LAST:event_fieldClaveAsignaturaFocusGained

    private void btnGuardarAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAgregarActionPerformed
        if ( ! valida().isEmpty()) {
            return;
        }
        asignaturas.add(materia);
        
        JOptionPane.showMessageDialog(null,"Guardado");
        
        materia = new Asignatura(); // Crear una nueva para que al guardar no remplace la informacion
        btnLimpiarActionPerformed(evt); // Propagacion de eventos, uno puede disparar a otro.
        
        capturador.muestraAsignaturas();
        capturador.updateList();
    }//GEN-LAST:event_btnGuardarAgregarActionPerformed

    private void btnGuardarFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFinalizarActionPerformed
        if ( ! valida().isEmpty()) {
            return;
        }
        
        if (asignaturas != null) {
            asignaturas.add(materia);
        }
        
        JOptionPane.showMessageDialog(null,"Guardado");
        
        capturador.muestraAsignaturas();
        capturador.updateList();
        
        dispose();
    }//GEN-LAST:event_btnGuardarFinalizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        fieldNombreAsignatura.setText("");
        fieldClaveAsignatura.setText("");
        jSlider1.setValue(1);
        jSpinner1.setValue(0);
        
        fieldNombreAsignatura.requestFocus(); //El campo para nombre asignatura se coniverta en el prota principal
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fieldNombreAsignatura.setText(
            materia.getNombreAsignatura()
        );
        
        fieldClaveAsignatura.setText(
            materia.getClaveAsignatura()
        );
        
        jSlider1.setValue(materia.getSemestre());
        jSpinner1.setValue(materia.getCreditos());
        
        if(materia.getNombreAsignatura() != null) {
            btnGuardarAgregar.setVisible(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private String valida(){
        String errores = "";
        try {
            String nombre = fieldNombreAsignatura.getText();
            if(nombre.trim().isEmpty() || nombre.trim().length() < 2) {
                errores += "\nEl nombre de la asignatura no puede ser vacío";
                errores += "\nEl nombre de la materia debe ser mayor a 1 caracter";
                fieldNombreAsignatura.setBackground(Color.yellow);
            }
            
            String clave = fieldClaveAsignatura.getText();
            if(clave.trim().isEmpty() || clave.trim().length() < 3) {
                errores += "\nLa clave de la asignatura no puede ser vacía";
                errores += "\nLa clave de la materia debe ser mayor a 2 caracteres";
                fieldClaveAsignatura.setBackground(Color.yellow);
            }
            
            Double creditos = (Double)jSpinner1.getValue();
            
            if( ! errores.isEmpty()) {
                throw new Exception("Errores de captura");
            }
            
            materia.setCreditos(creditos);
            materia.setNombreAsignatura(
                    fieldNombreAsignatura.getText()
            );
            materia.setClaveAsignatura(
                    fieldClaveAsignatura.getText()
            );
            materia.setSemestre(jSlider1.getValue());
            
        } catch (NumberFormatException nfe) {
            nfe.printStackTrace();
            errores += "\nError en los creditos";
            JOptionPane.showMessageDialog(
                null,
                "Debe corregir errores:\n" + errores,
                "Error al guardar",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                null,
                "Debe corregir errores:\n" + errores,
                "Error al guardar",
                JOptionPane.ERROR_MESSAGE
            );
        }
        return errores;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AsignaturaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAgregar;
    private javax.swing.JButton btnGuardarFinalizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextField fieldClaveAsignatura;
    private javax.swing.JTextField fieldNombreAsignatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelSemestre;
    // End of variables declaration//GEN-END:variables
}
