/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Practica3;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SubtemaPanel extends javax.swing.JPanel {

    private int indice;

    
    private Subtema subtema;
    private SubtemasFrame frame;
    private ArrayList<Subtema> subtemas;
    
    public SubtemaPanel() {
        initComponents();
    }
    
    public SubtemaPanel(SubtemasFrame frame, ArrayList<Subtema> subtemas,int indice) {
        initComponents();
        
        this.frame = frame;
        this.subtemas =  subtemas;
        this.subtema = subtemas.get(indice);
        
        labelTema.setText(
            subtema.getNumSubtema()+ "- " +
            subtema.getNombre()
        );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTema = new javax.swing.JLabel();
        btnEditarSubema = new javax.swing.JButton();
        btnBorrarSubtema = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelTema.setBackground(new java.awt.Color(255, 255, 255));
        labelTema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTema.setText("jLabel1");

        btnEditarSubema.setText("Editar");
        btnEditarSubema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSubemaActionPerformed(evt);
            }
        });

        btnBorrarSubtema.setForeground(new java.awt.Color(204, 0, 0));
        btnBorrarSubtema.setText("Borrar");
        btnBorrarSubtema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarSubtemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTema, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarSubema, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnBorrarSubtema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelTema, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEditarSubema, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarSubtema, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarSubemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSubemaActionPerformed
        subtema.setNombre(
            JOptionPane.showInputDialog(null,
                "Nuevo nombre de tema")
        );

        JOptionPane.showMessageDialog(null,
            "Tema agregado a la asignatura"
        );

        frame.mostrarSubtemas();
        updateUI();

    }//GEN-LAST:event_btnEditarSubemaActionPerformed

    private void btnBorrarSubtemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarSubtemaActionPerformed
        String message = "¿Estas seguro de eliminar el subtema " + subtema.getNombre() + "?";
        if(JOptionPane.showConfirmDialog(null,message) == JOptionPane.YES_OPTION){
            subtemas.remove(indice);
            JOptionPane.showMessageDialog(null, "Tema eliminado");
            frame.mostrarSubtemas();
        }
    }//GEN-LAST:event_btnBorrarSubtemaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarSubtema;
    private javax.swing.JButton btnEditarSubema;
    private javax.swing.JLabel labelTema;
    // End of variables declaration//GEN-END:variables
}
