/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Practica3;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TemaPanel extends javax.swing.JPanel {

    private int indice;

    
    private Tema tema;
    private TemasFrame frame;
    private ArrayList<Tema> temas;
    
    public TemaPanel() {
        initComponents();
    }
    
    public TemaPanel(TemasFrame frame, Tema tema) {
        initComponents();
        
        this.tema = tema;
        this.frame = frame;
        
        labelTema.setText(
            tema.getNumTema() + ". " +
            tema.getNombreTema()
        );
    }
    
    public TemaPanel(TemasFrame frame, ArrayList<Tema> temas,int indice) {
        initComponents();
        
        this.frame = frame;
        this.temas =  temas;
        this.tema = temas.get(indice);
        
        labelTema.setText(
            tema.getNumTema() + "- " +
            tema.getNombreTema()
        );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTema = new javax.swing.JLabel();
        btnEditarTema = new javax.swing.JButton();
        btnSubtemas = new javax.swing.JButton();
        btnBorrarTema = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelTema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTema.setText("jLabel1");

        btnEditarTema.setText("Editar");
        btnEditarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTemaActionPerformed(evt);
            }
        });

        btnSubtemas.setText("Subtemas");
        btnSubtemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtemasActionPerformed(evt);
            }
        });

        btnBorrarTema.setForeground(new java.awt.Color(204, 0, 0));
        btnBorrarTema.setText("Borrar");
        btnBorrarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTema, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubtemas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnBorrarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelTema, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEditarTema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubtemas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarTema)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTemaActionPerformed
        tema.setNombreTema(
                JOptionPane.showInputDialog(null,
                    "Nuevo nombre de tema")
        );
        
        JOptionPane.showMessageDialog(null,
                "Tema agregado a la asignatura"
        );
        
        frame.mostrarTemas();
        updateUI();
        
    }//GEN-LAST:event_btnEditarTemaActionPerformed

    private void btnBorrarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTemaActionPerformed
        String message = "¿Estas seguro de eliminar el tema " + tema.getNombreTema() + "?";
        if(JOptionPane.showConfirmDialog(null,message) == JOptionPane.YES_OPTION){
            temas.remove(indice);
            JOptionPane.showMessageDialog(null, "Tema eliminado");
            frame.mostrarTemas();
        }
    }//GEN-LAST:event_btnBorrarTemaActionPerformed

    private void btnSubtemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtemasActionPerformed
        new SubtemasFrame(tema)
                .setVisible(true);
    }//GEN-LAST:event_btnSubtemasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarTema;
    private javax.swing.JButton btnEditarTema;
    private javax.swing.JButton btnSubtemas;
    private javax.swing.JLabel labelTema;
    // End of variables declaration//GEN-END:variables
}
