/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Practica4;

import org.edisoncor.gui.panel.PanelLlamada;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;


public class ChatFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.
            getLogger(ChatFrame.class.getName());

    private GridLayout gridLayout = new GridLayout(1, 1);
    private Hilo hilo = new Hilo();

    private String ipDestino;
    private int puertoDestino, puertoOrigen;
    private boolean ejecuta = true;

    public ChatFrame() {
        initComponents();

        panelImage1.setLayout(gridLayout);

        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.decode("#E8F8F8"));

        try{
            javax.swing.UIManager.setLookAndFeel("net.sf.tinylaf.TinyLookAndFeel");
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelImage1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAPTema2\\src\\main\\java\\Practica4\\images\\chat.png")); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 312, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
                panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 449, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelImage1);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String msg = jTextField1.getText();
        jTextField1.setText("");

        muestraMsg(msg, true);
        enviaMsg(msg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String puertoReceptor = JOptionPane.showInputDialog(
                null,
                "Ingrese puerto de mensajes: ",
                "Puerto de receptor.",
                JOptionPane.QUESTION_MESSAGE
        );
        String destino = JOptionPane.showInputDialog(
                null,
                "Ingrese destino (IP: Puerto)",
                "Datos del destino.",
                JOptionPane.QUESTION_MESSAGE
        );
        puertoOrigen = Integer.parseInt(puertoReceptor);
        ipDestino = destino.split(":")[0];
        puertoDestino = Integer.parseInt(destino.split(":")[1]);

        hilo.execute();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(!hilo.isCancelled()){
            hilo.cancel(true);
            ejecuta = false;
        }
    }//GEN-LAST:event_formWindowClosing

    private void enviaMsg(String msg){
        try{
            Socket socket = new Socket(
                    ipDestino, puertoDestino
            );

            ObjectOutputStream oos = new ObjectOutputStream(
                    socket.getOutputStream()
            );

            oos.writeObject(msg);
            oos.close();
            socket.close();
        }catch (Exception e){
            e.printStackTrace();
        }
    }


    private void muestraMsg(String msg, boolean esEmisor){
        gridLayout.setRows(gridLayout.getRows() + 1);

        JLabel label = new JLabel(msg);
        PanelLlamada panelLlamada = new PanelLlamada();
        panelLlamada.setSize(300, 50);
        if (esEmisor){
            panelLlamada.setColorPrimario(new java.awt.Color(171, 234, 166));
            panelLlamada.setColorSecundario(new java.awt.Color(199, 234, 197));
            panelLlamada.setOrientacion(PanelLlamada.Orientacion.LEFT);
        }else{
            panelLlamada.setColorPrimario(new java.awt.Color(51, 153, 255));
            panelLlamada.setColorSecundario(new java.awt.Color(153, 204, 255));
            panelLlamada.setOrientacion(PanelLlamada.Orientacion.RIGHT);
        }
        panelLlamada.add(label);
        panelImage1.add(panelLlamada);
        panelImage1.setVisible(true);
        panelImage1.updateUI();
    }



    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChatFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables

    /** <h1> Hilo:</h1>
     *  <p> Un hilo infinito: este recibe mensajes</p>
     *
     */
    class Hilo extends SwingWorker {
        @Override
        protected Object doInBackground() throws Exception {
            while (ejecuta){
                try {
                    ServerSocket server = new ServerSocket(puertoOrigen);
                    Socket socket = server.accept();
                    ObjectInputStream ois = new ObjectInputStream(
                            socket.getInputStream()
                    );

                    String msg = "" + ois.readObject();

                    publish(msg);

                    ois.close();
                    socket.close();
                    server.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            return "";
        }

        /** <h1> Process </h1>
         *
         * @param chunks Chunks puede recibir un listado de cosas, no necesariamente en un objeto {@link List List}, se puede mandar así:
         *   <p> {@code publish(msg,"s","hola");}</p>
         *
         */

        @Override
        protected void process(java.util.List chunks) {
            super.process(chunks);
            String msg = "" + chunks.get(0);
            System.out.println("Mensaje recibido: " + msg);
            muestraMsg(msg, false);
        }

    }

}
