/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Practica4;

import Practica4.models.Producto;
import Practica4.models.Venta;
import Practica4.services.ProductoService;
import Practica4.services.VentaService;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.io.*;
import java.util.Calendar;
import javax.sound.sampled.*;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author michael
 */
public class TiendaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TiendaFrame.class.getName());

    private final String IMG_PATH = "src/main/java/Practica4/images/";
    private int index;
    
    private Producto producto;
    private ArrayList<Producto> listaProductos;
    private ArrayList<Venta> ventas;
    
    /**
     * Creates new form TiendaFrame
     */
    public TiendaFrame() {
        listaProductos = new ArrayList<>();
        ventas = new ArrayList<>();
        index = 0;
        
        initComponents();
        setLocationRelativeTo(null);

        
        
        try{
        javax.swing.UIManager.setLookAndFeel("net.sf.tinylaf.TinyLookAndFeel"); 
        } catch(Exception e) {
                e.printStackTrace();
        }
        
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        labelName = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        fieldBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mi tienda");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        panelImage1.setBackground(new java.awt.Color(255, 153, 153));
        panelImage1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelImage1.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        labelName.setFont(new java.awt.Font("Franklin Gothic Book", 0, 20)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 0, 0));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelName.setText("Nombre producto");

        btnPrev.setBackground(new java.awt.Color(102, 102, 255));
        btnPrev.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\Practica4\\images\\izquierda.png")); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(102, 102, 255));
        btnNext.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\Practica4\\images\\derecha.png")); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Fira Mono", 1, 15)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("Precio: ");

        labelQuantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelQuantity.setForeground(new java.awt.Color(0, 0, 0));
        labelQuantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelQuantity.setText(".");

        label2.setFont(new java.awt.Font("Fira Mono", 1, 15)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Unidades: ");

        labelPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPrice.setForeground(new java.awt.Color(0, 0, 0));
        labelPrice.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPrice.setText("$--.--");

        fieldBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        fieldBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        fieldBusqueda.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Inserte el nombre del producto:");

        btnBuscar.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVender.setBackground(new java.awt.Color(51, 204, 0));
        btnVender.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnVender.setForeground(new java.awt.Color(0, 0, 0));
        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(label2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelName)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(btnVender)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldBusqueda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelName)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label2)
                                    .addComponent(labelQuantity))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label1)
                                    .addComponent(labelPrice))
                                .addGap(24, 24, 24)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );

        jMenu1.setText("Archivo");

        jMenuItem2.setText("Inventario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Historial");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem3.setText("Acerca de...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new InventarioFrame(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new HistorialFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null,"Asbestos & NyE Software Inc. - 2025");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if( index > 0) {
            producto = listaProductos.get(index-1);
            index -= 1;
        }else if( index == 0){
            producto = listaProductos.get(listaProductos.size()-1);
            index = listaProductos.size()-1;
        }
        actualizarMostrador();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        actualizarListado();
        
        ventas = VentaService.getVentas();
    }//GEN-LAST:event_formWindowOpened

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if( index < listaProductos.size()-1) {
            producto = listaProductos.get(index+1);
            index += 1;
        }else if( index == listaProductos.size()-1){
            producto = listaProductos.get(0);
            index = 0;
        }
        actualizarMostrador();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String productoDeseado = fieldBusqueda.getText().toUpperCase();
        
        if(productoDeseado.length() < 1) {
            JOptionPane.showMessageDialog(null,
                "Caja de texto vacia",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        for(Producto p : listaProductos) {
            System.out.println(String.format("Busqueda: %s y Actual: %s", productoDeseado, p.getNombreProducto()));
            if(productoDeseado.equals(p.getNombreProducto().toUpperCase()) ){
                producto = p;
                index = listaProductos.indexOf(p);
                actualizarMostrador();
                fieldBusqueda.setText("");
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Tu producto que buscas no existe", "Producto no existente", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed

        JDialog dialog = new JDialog();
        dialog.setTitle("Vender: "+producto.getNombreProducto());
        dialog.setSize(300,300);
        dialog.setLocationRelativeTo(null);
        dialog.getContentPane().setLayout(
                new FlowLayout()
        );
        
        JLabel labelNombre = new JLabel(producto.getNombreProducto());
        labelNombre.setSize(300,25);
        labelNombre.setFont(new Font("Franklin Gothic Book", 0, 20));
        labelNombre.setForeground(Color.blue);
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dialog.getContentPane().add(labelNombre);
        
        JLabel labelPrecio = new JLabel(String.format("Precio: $%1$,.2f", producto.getPrecio()));
        labelPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18));
        labelPrecio.setForeground(Color.GREEN);
        labelPrecio.setSize(300,25);
        labelPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dialog.getContentPane().add(labelPrecio);
        
        JSpinner spinner = new JSpinner();
        spinner.setValue(1);
        
        spinner.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
                int cantidad = (int) spinner.getValue();
                Double precio = producto.getPrecio() * cantidad;
                labelPrecio.setText(String.format("Total: $%1$,.2f", precio));
            }
        });
        
        dialog.getContentPane().add(spinner);
        
        
        JButton btn = new JButton("Vender");
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int cantidad = (int) spinner.getValue();
                if(cantidad > 0 && cantidad <= producto.getCantidad()){
                    realizarVenta(producto, cantidad, (cantidad * producto.getPrecio()));
                }else{
                    JOptionPane.showMessageDialog(null,"No puedo vender menos de uno y mas del stock");
                }
            }
            
        });
        dialog.getContentPane().add(btn);
        
        
        
        dialog.setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed
    
    private void actualizarMostrador(){
        if(!listaProductos.isEmpty() || ! (listaProductos == null)) {
            
            jPanel1.setVisible(true);
            labelName.setText(producto.getNombreProducto());
            labelQuantity.setText(String.format("%s", producto.getCantidad()));
            labelPrice.setText(String.format("$%1$,.2f", producto.getPrecio()));
            
            String img = IMG_PATH + "no_image_2.jpg";
            if( ! producto.getFotoProducto().isEmpty() || ! (producto.getFotoProducto() == null)) {
                img = IMG_PATH + producto.getFotoProducto();
            }
            panelImage1.setIcon(
                new javax.swing.ImageIcon(
                    img
                )
            );
            panelImage1.updateUI();
        }
    }
    
    public void actualizarListado(){
        listaProductos = ProductoService.getLista();
        if(listaProductos.getFirst() != null) {
            producto = listaProductos.get(index);
            actualizarMostrador();
        }
    }
    
    public void realizarVenta(Producto producto, int cantidad, Double total){
        // Se obitiene la fecha actual en formato MySQL
        Calendar calendar = Calendar.getInstance();
        java.sql.Timestamp sqlTimestamp = 
            new java.sql.Timestamp(
                calendar.getTimeInMillis()
        );
        System.out.println("Producto vendido: " + producto.toString());
        System.out.println("Fecha venta: " + sqlTimestamp);
        
        // Se crea el objeto
        Venta venta = new Venta();
        venta.setProducto(producto);
        venta.setCantidadVendida(cantidad);
        venta.setTotal(total);
        venta.setFecha(sqlTimestamp.toString());
        
        // Se agrega a ventas y se escribe
        ventas.add(venta);
        
        if(VentaService.writeVentas(ventas)) {
            JOptionPane.showMessageDialog(null,"Venta realizada");
            
            try
            {
                File file = new File("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\Practica4\\extras\\money.wav");
                AudioInputStream audioIn = AudioSystem.getAudioInputStream(file);
                Clip clip = AudioSystem.getClip();
                clip.open(audioIn);
                clip.start();
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
            }
            
            actualizarStock(cantidad);
            
        } else {
            JOptionPane.showMessageDialog(null,"Error al vender");
        }
    }
    
    private void actualizarStock(int cantidad){
        listaProductos.get(index).setCantidad(producto.getCantidad() - cantidad);
        ProductoService.writeProductos(listaProductos);
        actualizarListado();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
        javax.swing.UIManager.setLookAndFeel("net.sf.tinylaf.TinyLookAndFeel"); 
        } catch(Exception e) {
                e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TiendaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnVender;
    private javax.swing.JTextField fieldBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelQuantity;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
