/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.subframes.panes;

import java.awt.Color;

/**
 *
 * @author User
 */
public class SelectRecordPane extends javax.swing.JPanel {

    /**
     * Creates new form SelectRecordPane
     */
    public SelectRecordPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage = new org.edisoncor.gui.panel.PanelImage();
        btnLeer = new javax.swing.JPanel();
        labelLeer = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelCat = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 188, 188));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\proyecto\\resources\\imgnotfound.png")); // NOI18N
        add(panelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 140));

        btnLeer.setBackground(new java.awt.Color(96, 243, 96));
        btnLeer.setPreferredSize(new java.awt.Dimension(106, 31));

        labelLeer.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelLeer.setForeground(new java.awt.Color(255, 255, 255));
        labelLeer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLeer.setText("LEER");
        labelLeer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLeer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLeerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLeerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLeerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLeerLayout = new javax.swing.GroupLayout(btnLeer);
        btnLeer.setLayout(btnLeerLayout);
        btnLeerLayout.setHorizontalGroup(
            btnLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLeerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnLeerLayout.setVerticalGroup(
            btnLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLeerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(btnLeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 60, -1));

        labelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(114, 114, 114));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Titulo");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        labelEstado.setBackground(new java.awt.Color(0, 0, 0));
        labelEstado.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(114, 114, 114));
        labelEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEstado.setText("Estado");
        add(labelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        labelCat.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelCat.setForeground(new java.awt.Color(114, 114, 114));
        labelCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCat.setText("Categoría");
        add(labelCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void labelLeerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLeerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelLeerMouseClicked

    private void labelLeerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLeerMouseEntered
        btnLeer.setBackground(new Color(146,246,146));
    }//GEN-LAST:event_labelLeerMouseEntered

    private void labelLeerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLeerMouseExited
        btnLeer.setBackground(new Color(96,243,96));
    }//GEN-LAST:event_labelLeerMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLeer;
    private javax.swing.JLabel labelCat;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelLeer;
    private javax.swing.JLabel labelTitulo;
    private org.edisoncor.gui.panel.PanelImage panelImage;
    // End of variables declaration//GEN-END:variables
}
