/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.subframes;

/**
 *
 * @author User
 */
public class RecordReaderPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecordReaderPanel
     */
    public RecordReaderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelImage = new org.edisoncor.gui.panel.PanelImage();
        labelTituloYAutor = new javax.swing.JLabel();
        labelEstadoYCategoria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelDescripción = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(216, 188, 188));
        bg.setMinimumSize(new java.awt.Dimension(762, 600));
        bg.setPreferredSize(new java.awt.Dimension(762, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(114, 114, 114));
        labelTitle.setText("Record Lecture Panel");
        bg.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\proyecto\\resources\\imgnotfound.png")); // NOI18N
        bg.add(panelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 180));

        labelTituloYAutor.setBackground(new java.awt.Color(0, 0, 0));
        labelTituloYAutor.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelTituloYAutor.setForeground(new java.awt.Color(114, 114, 114));
        labelTituloYAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloYAutor.setText("Titulo");
        bg.add(labelTituloYAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        labelEstadoYCategoria.setBackground(new java.awt.Color(0, 0, 0));
        labelEstadoYCategoria.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelEstadoYCategoria.setForeground(new java.awt.Color(114, 114, 114));
        labelEstadoYCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEstadoYCategoria.setText("Estado");
        bg.add(labelEstadoYCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(216, 188, 188));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(216, 188, 188));

        labelDescripción.setBackground(new java.awt.Color(216, 188, 188));
        labelDescripción.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelDescripción.setForeground(new java.awt.Color(114, 114, 114));
        labelDescripción.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDescripción.setText("Descripción");
        labelDescripción.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(labelDescripción);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 700, 370));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescripción;
    private javax.swing.JLabel labelEstadoYCategoria;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTituloYAutor;
    private org.edisoncor.gui.panel.PanelImage panelImage;
    // End of variables declaration//GEN-END:variables
}
