/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.subframes;

import java.awt.Color;

/**
 *
 * @author User
 */
public class RecordApproverPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminRecordPanel
     */
    public RecordApproverPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCat = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelImage = new org.edisoncor.gui.panel.PanelImage();
        fieldEstado = new javax.swing.JTextField();
        labelAprove = new javax.swing.JLabel();
        labelCrit3 = new javax.swing.JLabel();
        labelCrit1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        labelCancelar = new javax.swing.JLabel();
        btnAprove = new org.edisoncor.gui.panel.PanelImage();
        btnDeny = new org.edisoncor.gui.panel.PanelImage();
        fieldTitulo = new javax.swing.JTextField();
        labelCrit2 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        fieldCategoría = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDescripcion = new javax.swing.JTextField();

        setBackground(new java.awt.Color(216, 188, 188));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(216, 188, 188));
        bg.setMinimumSize(new java.awt.Dimension(762, 600));
        bg.setPreferredSize(new java.awt.Dimension(762, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(114, 114, 114));
        labelTitle.setText("Admin Record Panel");
        bg.add(labelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\proyecto\\resources\\imgnotfound.png")); // NOI18N
        bg.add(panelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 180));

        fieldEstado.setBackground(new java.awt.Color(255, 255, 255));
        fieldEstado.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldEstado.setForeground(new java.awt.Color(235, 233, 233));
        fieldEstado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldEstado.setText("Estado");
        fieldEstado.setBorder(null);
        fieldEstado.setEnabled(false);
        bg.add(fieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 300, -1));

        labelAprove.setBackground(new java.awt.Color(0, 0, 0));
        labelAprove.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelAprove.setForeground(new java.awt.Color(114, 114, 114));
        labelAprove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAprove.setText("¿Aprobar?");
        bg.add(labelAprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        labelCrit3.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelCrit3.setForeground(new java.awt.Color(114, 114, 114));
        labelCrit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCrit3.setText("Categoría");
        bg.add(labelCrit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        labelCrit1.setBackground(new java.awt.Color(0, 0, 0));
        labelCrit1.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelCrit1.setForeground(new java.awt.Color(114, 114, 114));
        labelCrit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCrit1.setText("Titulo");
        bg.add(labelCrit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(96, 243, 96));
        btnCancelar.setPreferredSize(new java.awt.Dimension(106, 31));

        labelCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        labelCancelar.setForeground(new java.awt.Color(255, 255, 255));
        labelCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCancelar.setText("CANCELAR");
        labelCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 90, -1));

        btnAprove.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\proyecto\\resources\\aprove.png")); // NOI18N

        javax.swing.GroupLayout btnAproveLayout = new javax.swing.GroupLayout(btnAprove);
        btnAprove.setLayout(btnAproveLayout);
        btnAproveLayout.setHorizontalGroup(
            btnAproveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        btnAproveLayout.setVerticalGroup(
            btnAproveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(btnAprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 30, 30));

        btnDeny.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\Programming\\JetBrains\\IntelliJ Projects\\Topicos Avanzados de Programacion\\TAP Tema 1\\src\\main\\java\\proyecto\\resources\\cancel.png")); // NOI18N

        javax.swing.GroupLayout btnDenyLayout = new javax.swing.GroupLayout(btnDeny);
        btnDeny.setLayout(btnDenyLayout);
        btnDenyLayout.setHorizontalGroup(
            btnDenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        btnDenyLayout.setVerticalGroup(
            btnDenyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(btnDeny, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 30, 30));

        fieldTitulo.setBackground(new java.awt.Color(255, 255, 255));
        fieldTitulo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldTitulo.setForeground(new java.awt.Color(235, 233, 233));
        fieldTitulo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldTitulo.setText("Título");
        fieldTitulo.setBorder(null);
        fieldTitulo.setEnabled(false);
        bg.add(fieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 300, -1));

        labelCrit2.setBackground(new java.awt.Color(0, 0, 0));
        labelCrit2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelCrit2.setForeground(new java.awt.Color(114, 114, 114));
        labelCrit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCrit2.setText("Estado");
        bg.add(labelCrit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        labelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        labelUsuario.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(114, 114, 114));
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setText("Usuario");
        bg.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        fieldCategoría.setBackground(new java.awt.Color(255, 255, 255));
        fieldCategoría.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldCategoría.setForeground(new java.awt.Color(235, 233, 233));
        fieldCategoría.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldCategoría.setText("Categoría");
        fieldCategoría.setBorder(null);
        fieldCategoría.setEnabled(false);
        bg.add(fieldCategoría, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 300, -1));

        fieldDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescripcion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldDescripcion.setForeground(new java.awt.Color(235, 233, 233));
        fieldDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldDescripcion.setText("Descripción");
        fieldDescripcion.setBorder(null);
        fieldDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(fieldDescripcion);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 700, 210));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void labelCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancelarMouseExited
        btnCancelar.setBackground(new Color(96,243,96));
    }//GEN-LAST:event_labelCancelarMouseExited

    private void labelCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancelarMouseEntered
        btnCancelar.setBackground(new Color(146,246,146));
    }//GEN-LAST:event_labelCancelarMouseEntered

    private void labelCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private org.edisoncor.gui.panel.PanelImage btnAprove;
    private javax.swing.JPanel btnCancelar;
    private org.edisoncor.gui.panel.PanelImage btnDeny;
    private javax.swing.JTextField fieldCategoría;
    private javax.swing.JTextField fieldDescripcion;
    private javax.swing.JTextField fieldEstado;
    private javax.swing.JTextField fieldTitulo;
    private javax.swing.ButtonGroup groupCat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAprove;
    private javax.swing.JLabel labelCancelar;
    private javax.swing.JLabel labelCrit1;
    private javax.swing.JLabel labelCrit2;
    private javax.swing.JLabel labelCrit3;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelUsuario;
    private org.edisoncor.gui.panel.PanelImage panelImage;
    // End of variables declaration//GEN-END:variables
}
